### ISSUE TITLE
declare command erroring when running pre-commit

### ISSUE THREAD

**Issue by ironScripter** [fabasoad/pre-commit-grype#21]
## Describe the bug
After installing for the first time and running I get this error

```
Grype Dir................................................................Failed
- hook id: grype-dir
- duration: 0.17s
- exit code: 2

/Users/<USERNAME>/.cache/pre-commit/repohqq3lmdz/src/main.sh: line 31: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

## Steps to Reproduce

1. Run 'pre-commit'
2. See error

## Config
```
    - repo: https://github.com/fabasoad/pre-commit-grype
      rev: v0.6.2
      hooks:
        - id: grype-dir
```

## Technical information (please complete the following information)

- OS: macOS 15.3 (24D60)
- `pre-commit-grype` version [e.g. 0.6.2]
